<div class="welcome-page" data-app="guest">
	<!-- <div class="welcome-page__slider" id="guest-slider">
		<div v-for="(img, ind) in images" class="slide" v-bind:class="{'show': ind == curr_ind}" v-bind:style="{'background-image': 'url(' + img + ')'}"></div>
	</div> -->
	<div class="welcome-page__body">
	<div class="home__box__info">
		<div class="home__box__info__circle" data-icon="home-circle" style=" background-image: url(themes/default/statics/img/home-circle.svg);"></div>
		<div class="home__box__info__points" data-icon="home-points" style=" background-image: url(themes/default/statics/img/home-points.svg);"></div>
			<h1 style="color: white;">Welcome to<br>
			our community</h1><br>
			<p style="color: #bdbdbd;">Fuse helps developers to build organized and well coded dashboards full of beautiful and rich modules. Join us and start building your application today.</p><br>
			<div class="home__box__info__avatars" style="display: flex">
				<div class="home__box__info__avatars__row">
					<figure class="image_container">
						<img src="themes/default/statics/img/1.jpg" width="42" height="42" alt="">
					</figure>
					<figure class="image_container">
						<img src="themes/default/statics/img/2.jpg" width="42" height="42" alt="">
					</figure>
					<figure class="image_container">
						<img src="themes/default/statics/img/3.jpg" width="42" height="42" alt="">
					</figure>
					<figure class="image_container">
						<img src="themes/default/statics/img/4.jpg" width="42" height="42" alt="">
					</figure>
				</div><br>
				<div class="home__box__info__avatars__text" style="padding-left: 20px">More than 17k people joined us, it's your turn</div>
			</div>
			<!-- <?php echo cl_template('main/footer'); ?> -->
	</div>
		<div class="home__box__controls">
			<div class="col-xxl-9 col-xl-10 col-12">
				<div class="row">
					<div class="col-xxl-6 col-xl-6 col-lg-6 col-md-12">
						<div class="welcome-page__rp">
							<div class="welcome-page__rp-inner">
								<div class="welcome-page-form">
									<div class="welcome-page-form__header" style="padding: 10px;">
										<a href="<?php echo cl_link('/'); ?>" class="logo">
											<img src="{%config site_logo%}" alt="Logo">
										</a>
										<!-- <h1>
											<?php echo  cl_translate("Welcome to {@site_name@}", array("site_name" => $cl["config"]["name"])); ?>
										</h1> -->
									</div>
									<div class="welcome-page-form__body" style="padding: 10px;">
										<div class="auth-form">
											<div class="auth-form-holder">
												<?php if ($cl["auth_type"] == "login"): ?>
													<?php echo cl_template('auth/login'); ?>
												<?php elseif($cl["auth_type"] == "forgot_pass"): ?>
													<?php echo cl_template('auth/reset_password'); ?>
												<?php elseif($cl["auth_type"] == "reset_pass" && not_empty($cl['em_code'])): ?>
													<?php echo cl_template('auth/new_password'); ?>
												<?php else: ?>
													<?php if ($cl['config']['user_signup'] == "on" || not_empty($cl["invite_code_status"])): ?>
														<?php echo cl_template('auth/register'); ?>
													<?php else: ?>
														<?php echo cl_template('auth/register_off'); ?>
													<?php endif; ?>
												<?php endif; ?>
											</div>	
										</div>
									</div>	
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- <div class="welcome-page__footer">
		<div class="row justify-content-center">
			<div class="col-xxl-9 col-xl-10 col-12">
				<div class="welcome-page__bp-wrapper">
					<div class="welcome-page__bp">
						<?php echo cl_template('main/footer'); ?>
					</div>
				</div>
			</div>
		</div>
	</div> -->
</div>

<script>
	$(document).ready(function() {
		var _app = $("[data-app='guest']");

		new Vue({
			el: "#guest-slider",
			data: {
				curr_ind: 0,
				images: <?php echo cl_minify_js(json($cl["slider_imgs"], true)); ?>
			},
			created: function() {
				var _app_ = this;

				if (_app_.images.length >= 2) {
					setInterval(function() {

						if (_app_.curr_ind >= _app_.images.length - 1) {
							_app_.curr_ind = 0;
						}
						else{
							_app_.curr_ind += 1;
						}

					}, 3000);
				}
			}
		});

		
	});
</script>

<?php echo cl_template('auth/scripts/app_master_script'); ?>

